version: '3.5'
services: 
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    env_file: 
      - ../env/config.env
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf